# Generated by Django 4.1.2 on 2022-10-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_event_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hackthon_participant",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
