# Generated by Django 4.1.2 on 2022-10-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_user_hackthon_participant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_deadline",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
    ]
