# Generated by Django 4.1.2 on 2022-10-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="/images/avatar.png", upload_to=""),
        ),
    ]
